### ISSUE TITLE
Search not linking to correct pages

### ISSUE THREAD

**Issue by obycode** [stacks-network/docs#1573]
**Describe the issue**
There seems to be a problem with the links from the search (Cmd-K) on the Clarity docs. When it should link to https://docs.stacks.co/docs/clarity/language-functions#unwrap for example, it instead is linking to https://docs.stacks.co/docs/write-smart-contracts/clarity-language/language-functions#unwrap

**Comment by wileyj** [comment]
I think i undertand what happened here - using algolia open source indexer, there's no way to re-index on demand since it runs via cron (etc). 
When the docs site was updated, it quite literally broke most of the existing index and it simply took a little time for the refresh to happen. 

luckily, changes like that merge are not common - i'm also looking at some options to give us more control over the search index as well
